server:
  port: 8443


#server: 
#  port: 443 #项目端口
#  ssl: 
#    key-store: classpath:2131938_www.lujinshan.top.pfx
#    key-store-password: C2Krt7Wh
#    key-store-type: PKCS12  

mybatis-plus:
  mapper-locations: classpath*:com/md/**/mapping/*.xml
  typeAliasesPackage: com.md
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf8&useSSL=false
#      url: jdbc:mysql://47.101.205.185:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  resources: 
#      static-locations: file:/home/image
     static-locations: file:E:\大四\大四下\毕设\Shop\image

logging:
  path: logs/
  file: guns-rest.log
